esp32_motor_controller:
  ros__parameters:
    uart_port: "/dev/ttyTHS1"
    baudrate: 115200
    wheel_separation: 0.381
    wheel_radius: 0.065
    max_linear_vel: 1.11
    max_angular_vel: 2.0
    
ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    two_d_mode: true   # 如果你的機器人在平面上運動（差速驅動建議開啟）
    publish_tf: true

    # 輸入 topic
    odom0: /odom_raw
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  true,  true,  false,
                  false, false, false]

    # IMU heading 來源
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # 輸出 topic
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

